services:
  php:
    container_name: symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      DATABASE_URL: ${DATABASE_URL:-mysql://symfony:symfony@db:3306/followjob?serverVersion=8.0}

  db:
    container_name: followjob_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: followjob
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - followjob_db_data:/var/lib/mysql

  adminer:
    container_name: followjob_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  followjob_db_data:
