services:
  symfony_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      - APP_ENV=dev
    volumes:
      - type: bind
        source: .
        target: /app

  symfony_db:
    image: mysql:8.0
    container_name: symfony_db
    command: --default-authentication-plugin=mysql_native_password --performance_schema=0 --innodb_buffer_pool_size=64M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: followjob
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - followjob_follow_job_database_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: symfony_adminer
    ports:
      - "8080:8080"
    depends_on:
      - symfony_db

volumes:
  followjob_follow_job_database_data:
    external: true
