version: "3.8"

services:
  db:
    container_name: followjob_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: followjob
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - followjob_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root"]
      interval: 5s
      timeout: 5s
      retries: 10

  php:
    container_name: symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: mysql://symfony:symfony@db:3306/followjob?serverVersion=8.0
    healthcheck:
      test: ["CMD-SHELL", "php -r 'echo \"OK\";'"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: followjob_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  followjob_db_data:
