services:
  symfony_php:
    container_name: symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: followjob_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: followjob_db
      MYSQL_USER: followjob_user
      MYSQL_PASSWORD: followjob_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - followjob_db_data:/var/lib/mysql

  adminer:
    container_name: followjob_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  followjob_db_data:
