version: "3.8"

services:
  symfony_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    volumes:
      - type: bind
        source: .
        target: /app

  symfony_db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: followjob
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - follow_job_database_data:/var/lib/mysql

volumes:
  follow_job_database_data:
